-- MOVIDO — Gate final §3 (2026-08-25).
--
-- `seed_demo_family_profiles` es schema REAL (la app la llama en
-- `loadDemoFamily`), así que vive en la migración
-- `supabase/migrations/0024_demo_family_function.sql`, no acá.
-- Este archivo queda solo como puntero para no romper referencias viejas.
-- Regla: schema de test == schema producible mediante migraciones.
