-- =============================================================================
-- HagoTuFila · Semilla geográfica: regiones y comunas de Chile
-- =============================================================================
-- GENERADO AUTOMÁTICAMENTE. No editar a mano.
-- Fuente: src/lib/geo/chile.ts · Regenerar con: npm run seed:geo
-- =============================================================================

insert into public.countries (code, name, currency, default_timezone)
values ('CL', 'Chile', 'CLP', 'America/Santiago')
on conflict (code) do nothing;

insert into public.regions (code, country_code, name, short_name, ordinal, timezone, sort_order)
values
  ('15', 'CL', 'Arica y Parinacota', 'Arica y Parinacota', 'XV', 'America/Santiago', 1),
  ('01', 'CL', 'Tarapacá', 'Tarapacá', 'I', 'America/Santiago', 2),
  ('02', 'CL', 'Antofagasta', 'Antofagasta', 'II', 'America/Santiago', 3),
  ('03', 'CL', 'Atacama', 'Atacama', 'III', 'America/Santiago', 4),
  ('04', 'CL', 'Coquimbo', 'Coquimbo', 'IV', 'America/Santiago', 5),
  ('05', 'CL', 'Valparaíso', 'Valparaíso', 'V', 'America/Santiago', 6),
  ('13', 'CL', 'Región Metropolitana de Santiago', 'Metropolitana', 'RM', 'America/Santiago', 7),
  ('06', 'CL', 'Libertador General Bernardo O''Higgins', 'O''Higgins', 'VI', 'America/Santiago', 8),
  ('07', 'CL', 'Maule', 'Maule', 'VII', 'America/Santiago', 9),
  ('16', 'CL', 'Ñuble', 'Ñuble', 'XVI', 'America/Santiago', 10),
  ('08', 'CL', 'Biobío', 'Biobío', 'VIII', 'America/Santiago', 11),
  ('09', 'CL', 'La Araucanía', 'Araucanía', 'IX', 'America/Santiago', 12),
  ('14', 'CL', 'Los Ríos', 'Los Ríos', 'XIV', 'America/Santiago', 13),
  ('10', 'CL', 'Los Lagos', 'Los Lagos', 'X', 'America/Santiago', 14),
  ('11', 'CL', 'Aysén del General Carlos Ibáñez del Campo', 'Aysén', 'XI', 'America/Santiago', 15),
  ('12', 'CL', 'Magallanes y de la Antártica Chilena', 'Magallanes', 'XII', 'America/Punta_Arenas', 16)
on conflict (code) do nothing;

insert into public.communes (code, region_code, name, timezone)
values
  ('15-arica', '15', 'Arica', null),
  ('15-camarones', '15', 'Camarones', null),
  ('15-general-lagos', '15', 'General Lagos', null),
  ('15-putre', '15', 'Putre', null),
  ('01-alto-hospicio', '01', 'Alto Hospicio', null),
  ('01-camina', '01', 'Camiña', null),
  ('01-colchane', '01', 'Colchane', null),
  ('01-huara', '01', 'Huara', null),
  ('01-iquique', '01', 'Iquique', null),
  ('01-pica', '01', 'Pica', null),
  ('01-pozo-almonte', '01', 'Pozo Almonte', null),
  ('02-antofagasta', '02', 'Antofagasta', null),
  ('02-calama', '02', 'Calama', null),
  ('02-maria-elena', '02', 'María Elena', null),
  ('02-mejillones', '02', 'Mejillones', null),
  ('02-ollague', '02', 'Ollagüe', null),
  ('02-san-pedro-de-atacama', '02', 'San Pedro de Atacama', null),
  ('02-sierra-gorda', '02', 'Sierra Gorda', null),
  ('02-taltal', '02', 'Taltal', null),
  ('02-tocopilla', '02', 'Tocopilla', null),
  ('03-alto-del-carmen', '03', 'Alto del Carmen', null),
  ('03-caldera', '03', 'Caldera', null),
  ('03-chanaral', '03', 'Chañaral', null),
  ('03-copiapo', '03', 'Copiapó', null),
  ('03-diego-de-almagro', '03', 'Diego de Almagro', null),
  ('03-freirina', '03', 'Freirina', null),
  ('03-huasco', '03', 'Huasco', null),
  ('03-tierra-amarilla', '03', 'Tierra Amarilla', null),
  ('03-vallenar', '03', 'Vallenar', null),
  ('04-andacollo', '04', 'Andacollo', null),
  ('04-canela', '04', 'Canela', null),
  ('04-combarbala', '04', 'Combarbalá', null),
  ('04-coquimbo', '04', 'Coquimbo', null),
  ('04-illapel', '04', 'Illapel', null),
  ('04-la-higuera', '04', 'La Higuera', null),
  ('04-la-serena', '04', 'La Serena', null),
  ('04-los-vilos', '04', 'Los Vilos', null),
  ('04-monte-patria', '04', 'Monte Patria', null),
  ('04-ovalle', '04', 'Ovalle', null),
  ('04-paihuano', '04', 'Paihuano', null),
  ('04-punitaqui', '04', 'Punitaqui', null),
  ('04-rio-hurtado', '04', 'Río Hurtado', null),
  ('04-salamanca', '04', 'Salamanca', null),
  ('04-vicuna', '04', 'Vicuña', null),
  ('05-algarrobo', '05', 'Algarrobo', null),
  ('05-cabildo', '05', 'Cabildo', null),
  ('05-calera', '05', 'Calera', null),
  ('05-calle-larga', '05', 'Calle Larga', null),
  ('05-cartagena', '05', 'Cartagena', null),
  ('05-casablanca', '05', 'Casablanca', null),
  ('05-catemu', '05', 'Catemu', null),
  ('05-concon', '05', 'Concón', null),
  ('05-el-quisco', '05', 'El Quisco', null),
  ('05-el-tabo', '05', 'El Tabo', null),
  ('05-hijuelas', '05', 'Hijuelas', null),
  ('05-isla-de-pascua', '05', 'Isla de Pascua', 'Pacific/Easter'),
  ('05-juan-fernandez', '05', 'Juan Fernández', 'America/Santiago'),
  ('05-la-cruz', '05', 'La Cruz', null),
  ('05-la-ligua', '05', 'La Ligua', null),
  ('05-limache', '05', 'Limache', null),
  ('05-llaillay', '05', 'Llaillay', null),
  ('05-los-andes', '05', 'Los Andes', null),
  ('05-nogales', '05', 'Nogales', null),
  ('05-olmue', '05', 'Olmué', null),
  ('05-panquehue', '05', 'Panquehue', null),
  ('05-papudo', '05', 'Papudo', null),
  ('05-petorca', '05', 'Petorca', null),
  ('05-puchuncavi', '05', 'Puchuncaví', null),
  ('05-putaendo', '05', 'Putaendo', null),
  ('05-quillota', '05', 'Quillota', null),
  ('05-quilpue', '05', 'Quilpué', null),
  ('05-quintero', '05', 'Quintero', null),
  ('05-rinconada', '05', 'Rinconada', null),
  ('05-san-antonio', '05', 'San Antonio', null),
  ('05-san-esteban', '05', 'San Esteban', null),
  ('05-san-felipe', '05', 'San Felipe', null),
  ('05-santa-maria', '05', 'Santa María', null),
  ('05-santo-domingo', '05', 'Santo Domingo', null),
  ('05-valparaiso', '05', 'Valparaíso', null),
  ('05-villa-alemana', '05', 'Villa Alemana', null),
  ('05-vina-del-mar', '05', 'Viña del Mar', null),
  ('05-zapallar', '05', 'Zapallar', null),
  ('13-alhue', '13', 'Alhué', null),
  ('13-buin', '13', 'Buin', null),
  ('13-calera-de-tango', '13', 'Calera de Tango', null),
  ('13-cerrillos', '13', 'Cerrillos', null),
  ('13-cerro-navia', '13', 'Cerro Navia', null),
  ('13-colina', '13', 'Colina', null),
  ('13-conchali', '13', 'Conchalí', null),
  ('13-curacavi', '13', 'Curacaví', null),
  ('13-el-bosque', '13', 'El Bosque', null),
  ('13-el-monte', '13', 'El Monte', null),
  ('13-estacion-central', '13', 'Estación Central', null),
  ('13-huechuraba', '13', 'Huechuraba', null),
  ('13-independencia', '13', 'Independencia', null),
  ('13-isla-de-maipo', '13', 'Isla de Maipo', null),
  ('13-la-cisterna', '13', 'La Cisterna', null),
  ('13-la-florida', '13', 'La Florida', null),
  ('13-la-granja', '13', 'La Granja', null),
  ('13-la-pintana', '13', 'La Pintana', null),
  ('13-la-reina', '13', 'La Reina', null),
  ('13-lampa', '13', 'Lampa', null),
  ('13-las-condes', '13', 'Las Condes', null),
  ('13-lo-barnechea', '13', 'Lo Barnechea', null),
  ('13-lo-espejo', '13', 'Lo Espejo', null),
  ('13-lo-prado', '13', 'Lo Prado', null),
  ('13-macul', '13', 'Macul', null),
  ('13-maipu', '13', 'Maipú', null),
  ('13-maria-pinto', '13', 'María Pinto', null),
  ('13-melipilla', '13', 'Melipilla', null),
  ('13-nunoa', '13', 'Ñuñoa', null),
  ('13-padre-hurtado', '13', 'Padre Hurtado', null),
  ('13-paine', '13', 'Paine', null),
  ('13-pedro-aguirre-cerda', '13', 'Pedro Aguirre Cerda', null),
  ('13-penaflor', '13', 'Peñaflor', null),
  ('13-penalolen', '13', 'Peñalolén', null),
  ('13-pirque', '13', 'Pirque', null),
  ('13-providencia', '13', 'Providencia', null),
  ('13-pudahuel', '13', 'Pudahuel', null),
  ('13-puente-alto', '13', 'Puente Alto', null),
  ('13-quilicura', '13', 'Quilicura', null),
  ('13-quinta-normal', '13', 'Quinta Normal', null),
  ('13-recoleta', '13', 'Recoleta', null),
  ('13-renca', '13', 'Renca', null),
  ('13-san-bernardo', '13', 'San Bernardo', null),
  ('13-san-joaquin', '13', 'San Joaquín', null),
  ('13-san-jose-de-maipo', '13', 'San José de Maipo', null),
  ('13-san-miguel', '13', 'San Miguel', null),
  ('13-san-pedro', '13', 'San Pedro', null),
  ('13-san-ramon', '13', 'San Ramón', null),
  ('13-santiago', '13', 'Santiago', null),
  ('13-talagante', '13', 'Talagante', null),
  ('13-tiltil', '13', 'Tiltil', null),
  ('13-vitacura', '13', 'Vitacura', null),
  ('06-chepica', '06', 'Chépica', null),
  ('06-chimbarongo', '06', 'Chimbarongo', null),
  ('06-codegua', '06', 'Codegua', null),
  ('06-coinco', '06', 'Coinco', null),
  ('06-coltauco', '06', 'Coltauco', null),
  ('06-donihue', '06', 'Doñihue', null),
  ('06-graneros', '06', 'Graneros', null),
  ('06-la-estrella', '06', 'La Estrella', null),
  ('06-las-cabras', '06', 'Las Cabras', null),
  ('06-litueche', '06', 'Litueche', null),
  ('06-lolol', '06', 'Lolol', null),
  ('06-machali', '06', 'Machalí', null),
  ('06-malloa', '06', 'Malloa', null),
  ('06-marchihue', '06', 'Marchihue', null),
  ('06-mostazal', '06', 'Mostazal', null),
  ('06-nancagua', '06', 'Nancagua', null),
  ('06-navidad', '06', 'Navidad', null),
  ('06-olivar', '06', 'Olivar', null),
  ('06-palmilla', '06', 'Palmilla', null),
  ('06-paredones', '06', 'Paredones', null),
  ('06-peralillo', '06', 'Peralillo', null),
  ('06-peumo', '06', 'Peumo', null),
  ('06-pichidegua', '06', 'Pichidegua', null),
  ('06-pichilemu', '06', 'Pichilemu', null),
  ('06-placilla', '06', 'Placilla', null),
  ('06-pumanque', '06', 'Pumanque', null),
  ('06-quinta-de-tilcoco', '06', 'Quinta de Tilcoco', null),
  ('06-rancagua', '06', 'Rancagua', null),
  ('06-rengo', '06', 'Rengo', null),
  ('06-requinoa', '06', 'Requínoa', null),
  ('06-san-fernando', '06', 'San Fernando', null),
  ('06-san-vicente', '06', 'San Vicente', null),
  ('06-santa-cruz', '06', 'Santa Cruz', null),
  ('07-cauquenes', '07', 'Cauquenes', null),
  ('07-chanco', '07', 'Chanco', null),
  ('07-colbun', '07', 'Colbún', null),
  ('07-constitucion', '07', 'Constitución', null),
  ('07-curepto', '07', 'Curepto', null),
  ('07-curico', '07', 'Curicó', null),
  ('07-empedrado', '07', 'Empedrado', null),
  ('07-hualane', '07', 'Hualañé', null),
  ('07-licanten', '07', 'Licantén', null),
  ('07-linares', '07', 'Linares', null),
  ('07-longavi', '07', 'Longaví', null),
  ('07-maule', '07', 'Maule', null),
  ('07-molina', '07', 'Molina', null),
  ('07-parral', '07', 'Parral', null),
  ('07-pelarco', '07', 'Pelarco', null),
  ('07-pelluhue', '07', 'Pelluhue', null),
  ('07-pencahue', '07', 'Pencahue', null),
  ('07-rauco', '07', 'Rauco', null),
  ('07-retiro', '07', 'Retiro', null),
  ('07-rio-claro', '07', 'Río Claro', null),
  ('07-romeral', '07', 'Romeral', null),
  ('07-sagrada-familia', '07', 'Sagrada Familia', null),
  ('07-san-clemente', '07', 'San Clemente', null),
  ('07-san-javier', '07', 'San Javier', null),
  ('07-san-rafael', '07', 'San Rafael', null),
  ('07-talca', '07', 'Talca', null),
  ('07-teno', '07', 'Teno', null),
  ('07-vichuquen', '07', 'Vichuquén', null),
  ('07-villa-alegre', '07', 'Villa Alegre', null),
  ('07-yerbas-buenas', '07', 'Yerbas Buenas', null),
  ('16-bulnes', '16', 'Bulnes', null),
  ('16-chillan', '16', 'Chillán', null),
  ('16-chillan-viejo', '16', 'Chillán Viejo', null),
  ('16-cobquecura', '16', 'Cobquecura', null),
  ('16-coelemu', '16', 'Coelemu', null),
  ('16-coihueco', '16', 'Coihueco', null),
  ('16-el-carmen', '16', 'El Carmen', null),
  ('16-ninhue', '16', 'Ninhue', null),
  ('16-niquen', '16', 'Ñiquén', null),
  ('16-pemuco', '16', 'Pemuco', null),
  ('16-pinto', '16', 'Pinto', null),
  ('16-portezuelo', '16', 'Portezuelo', null),
  ('16-quillon', '16', 'Quillón', null),
  ('16-quirihue', '16', 'Quirihue', null),
  ('16-ranquil', '16', 'Ránquil', null),
  ('16-san-carlos', '16', 'San Carlos', null),
  ('16-san-fabian', '16', 'San Fabián', null),
  ('16-san-ignacio', '16', 'San Ignacio', null),
  ('16-san-nicolas', '16', 'San Nicolás', null),
  ('16-treguaco', '16', 'Treguaco', null),
  ('16-yungay', '16', 'Yungay', null),
  ('08-alto-biobio', '08', 'Alto Biobío', null),
  ('08-antuco', '08', 'Antuco', null),
  ('08-arauco', '08', 'Arauco', null),
  ('08-cabrero', '08', 'Cabrero', null),
  ('08-canete', '08', 'Cañete', null),
  ('08-chiguayante', '08', 'Chiguayante', null),
  ('08-concepcion', '08', 'Concepción', null),
  ('08-contulmo', '08', 'Contulmo', null),
  ('08-coronel', '08', 'Coronel', null),
  ('08-curanilahue', '08', 'Curanilahue', null),
  ('08-florida', '08', 'Florida', null),
  ('08-hualpen', '08', 'Hualpén', null),
  ('08-hualqui', '08', 'Hualqui', null),
  ('08-laja', '08', 'Laja', null),
  ('08-lebu', '08', 'Lebu', null),
  ('08-los-alamos', '08', 'Los Álamos', null),
  ('08-los-angeles', '08', 'Los Ángeles', null),
  ('08-lota', '08', 'Lota', null),
  ('08-mulchen', '08', 'Mulchén', null),
  ('08-nacimiento', '08', 'Nacimiento', null),
  ('08-negrete', '08', 'Negrete', null),
  ('08-penco', '08', 'Penco', null),
  ('08-quilaco', '08', 'Quilaco', null),
  ('08-quilleco', '08', 'Quilleco', null),
  ('08-san-pedro-de-la-paz', '08', 'San Pedro de la Paz', null),
  ('08-san-rosendo', '08', 'San Rosendo', null),
  ('08-santa-barbara', '08', 'Santa Bárbara', null),
  ('08-santa-juana', '08', 'Santa Juana', null),
  ('08-talcahuano', '08', 'Talcahuano', null),
  ('08-tirua', '08', 'Tirúa', null),
  ('08-tome', '08', 'Tomé', null),
  ('08-tucapel', '08', 'Tucapel', null),
  ('08-yumbel', '08', 'Yumbel', null),
  ('09-angol', '09', 'Angol', null),
  ('09-carahue', '09', 'Carahue', null),
  ('09-cholchol', '09', 'Cholchol', null),
  ('09-collipulli', '09', 'Collipulli', null),
  ('09-cunco', '09', 'Cunco', null),
  ('09-curacautin', '09', 'Curacautín', null),
  ('09-curarrehue', '09', 'Curarrehue', null),
  ('09-ercilla', '09', 'Ercilla', null),
  ('09-freire', '09', 'Freire', null),
  ('09-galvarino', '09', 'Galvarino', null),
  ('09-gorbea', '09', 'Gorbea', null),
  ('09-lautaro', '09', 'Lautaro', null),
  ('09-loncoche', '09', 'Loncoche', null),
  ('09-lonquimay', '09', 'Lonquimay', null),
  ('09-los-sauces', '09', 'Los Sauces', null),
  ('09-lumaco', '09', 'Lumaco', null),
  ('09-melipeuco', '09', 'Melipeuco', null),
  ('09-nueva-imperial', '09', 'Nueva Imperial', null),
  ('09-padre-las-casas', '09', 'Padre Las Casas', null),
  ('09-perquenco', '09', 'Perquenco', null),
  ('09-pitrufquen', '09', 'Pitrufquén', null),
  ('09-pucon', '09', 'Pucón', null),
  ('09-puren', '09', 'Purén', null),
  ('09-renaico', '09', 'Renaico', null),
  ('09-saavedra', '09', 'Saavedra', null),
  ('09-temuco', '09', 'Temuco', null),
  ('09-teodoro-schmidt', '09', 'Teodoro Schmidt', null),
  ('09-tolten', '09', 'Toltén', null),
  ('09-traiguen', '09', 'Traiguén', null),
  ('09-victoria', '09', 'Victoria', null),
  ('09-vilcun', '09', 'Vilcún', null),
  ('09-villarrica', '09', 'Villarrica', null),
  ('14-corral', '14', 'Corral', null),
  ('14-futrono', '14', 'Futrono', null),
  ('14-la-union', '14', 'La Unión', null),
  ('14-lago-ranco', '14', 'Lago Ranco', null),
  ('14-lanco', '14', 'Lanco', null),
  ('14-los-lagos', '14', 'Los Lagos', null),
  ('14-mafil', '14', 'Máfil', null),
  ('14-mariquina', '14', 'Mariquina', null),
  ('14-paillaco', '14', 'Paillaco', null),
  ('14-panguipulli', '14', 'Panguipulli', null),
  ('14-rio-bueno', '14', 'Río Bueno', null),
  ('14-valdivia', '14', 'Valdivia', null),
  ('10-ancud', '10', 'Ancud', null),
  ('10-calbuco', '10', 'Calbuco', null),
  ('10-castro', '10', 'Castro', null),
  ('10-chaiten', '10', 'Chaitén', null),
  ('10-chonchi', '10', 'Chonchi', null),
  ('10-cochamo', '10', 'Cochamó', null),
  ('10-curaco-de-velez', '10', 'Curaco de Vélez', null),
  ('10-dalcahue', '10', 'Dalcahue', null),
  ('10-fresia', '10', 'Fresia', null),
  ('10-frutillar', '10', 'Frutillar', null),
  ('10-futaleufu', '10', 'Futaleufú', null),
  ('10-hualaihue', '10', 'Hualaihué', null),
  ('10-llanquihue', '10', 'Llanquihue', null),
  ('10-los-muermos', '10', 'Los Muermos', null),
  ('10-maullin', '10', 'Maullín', null),
  ('10-osorno', '10', 'Osorno', null),
  ('10-palena', '10', 'Palena', null),
  ('10-puerto-montt', '10', 'Puerto Montt', null),
  ('10-puerto-octay', '10', 'Puerto Octay', null),
  ('10-puerto-varas', '10', 'Puerto Varas', null),
  ('10-puqueldon', '10', 'Puqueldón', null),
  ('10-purranque', '10', 'Purranque', null),
  ('10-puyehue', '10', 'Puyehue', null),
  ('10-queilen', '10', 'Queilén', null),
  ('10-quellon', '10', 'Quellón', null),
  ('10-quemchi', '10', 'Quemchi', null),
  ('10-quinchao', '10', 'Quinchao', null),
  ('10-rio-negro', '10', 'Río Negro', null),
  ('10-san-juan-de-la-costa', '10', 'San Juan de la Costa', null),
  ('10-san-pablo', '10', 'San Pablo', null),
  ('11-aysen', '11', 'Aysén', null),
  ('11-chile-chico', '11', 'Chile Chico', null),
  ('11-cisnes', '11', 'Cisnes', null),
  ('11-cochrane', '11', 'Cochrane', null),
  ('11-coyhaique', '11', 'Coyhaique', null),
  ('11-guaitecas', '11', 'Guaitecas', null),
  ('11-lago-verde', '11', 'Lago Verde', null),
  ('11-o-higgins', '11', 'O''Higgins', null),
  ('11-rio-ibanez', '11', 'Río Ibáñez', null),
  ('11-tortel', '11', 'Tortel', null),
  ('12-antartica', '12', 'Antártica', null),
  ('12-cabo-de-hornos', '12', 'Cabo de Hornos', null),
  ('12-laguna-blanca', '12', 'Laguna Blanca', null),
  ('12-natales', '12', 'Natales', null),
  ('12-porvenir', '12', 'Porvenir', null),
  ('12-primavera', '12', 'Primavera', null),
  ('12-punta-arenas', '12', 'Punta Arenas', null),
  ('12-rio-verde', '12', 'Río Verde', null),
  ('12-san-gregorio', '12', 'San Gregorio', null),
  ('12-timaukel', '12', 'Timaukel', null),
  ('12-torres-del-paine', '12', 'Torres del Paine', null)
on conflict (code) do nothing;
